services:
  discord_bot:
    build:
      context: ./InaBot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "sh /app/banners/InaBot.sh && uv run main.py"
    env_file:
      - ./InaBot/.env
    volumes:
      - webdata:/app/data

volumes:
  webdata: